# Generated by Django 4.2.30 on 2026-04-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
